### PR TITLE
Workshop 2 Questionnaire

### PR DESCRIPTION
**Pull request by Adg0**

### CODE REVIEW

**Comment by kasperpawlowski** [comment]
Could you provide us with the email address you used to register for the Encode workshop?

**Comment by Adg0** [comment]
Okay thanks, I registered with ***@***.*** for the workshop.

**Comment by kasperpawlowski** [comment]
@Adg0 due to some reason the email is redacted. could you please try one more time?
image

**Comment by Adg0** [comment]
Oh it cause I replied in the email notification. my email is kalebbirru@gmail.com

**Pull request closed without merging**
