### PR TITLE
Workshop 2 Questionnaire

### PR DESCRIPTION
**Pull request by adapole**

### CODE REVIEW

**Comment by kasperpawlowski** [comment]
Could you provide us with the email address you used to register for the Encode workshop?

**Comment by adapole** [comment]
Thanks, the email I registered with is ***@***.***

**Comment by kasperpawlowski** [comment]
@adapole due to some reason the email is redacted. could you please try one more time?
image

**Comment by adapole** [comment]
Sure, the registered email is
eyassubn@gmail.com

**Pull request closed without merging**
